import { Head, Link } from '@inertiajs/react';
import { ArrowLeft, Printer } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Card, CardContent } from '@/components/ui/card';
import { formatCurrency, formatNumber } from '@/lib/format';

interface ReceiptItem { id: number; name: string; unit: string | null; quantity: number; price: number; total: number }
interface Receipt { id: number; number: string; createdAt: string | null; buyer: string; cashier: string; total: number; paid: number; change: number; paymentMethod: string; items: ReceiptItem[] }

export default function DirectSaleReceipt({ receipt, indexUrl }: { receipt: Receipt; indexUrl: string }) {
    return <><Head title={`Nota ${receipt.number}`} /><div className="mx-auto max-w-xl space-y-5"><div className="flex items-center justify-between print:hidden"><Button asChild size="sm" variant="ghost"><Link href={indexUrl}><ArrowLeft className="size-4" />Kembali ke penjualan</Link></Button><Button onClick={() => window.print()}><Printer className="size-4" />Cetak nota</Button></div><Card className="receipt-card border-slate-200 shadow-sm"><CardContent className="receipt-content p-6 font-mono text-xs text-slate-800"><header className="border-b border-dashed border-slate-300 pb-4 text-center"><p className="text-base font-bold text-slate-950">Klinik Pratama</p><p className="mt-1 text-[10px] uppercase tracking-wide text-slate-500">Instalasi farmasi</p><p className="mt-1 text-[10px] text-slate-500">Bukti transaksi penjualan obat</p></header><section className="space-y-1 border-b border-dashed border-slate-300 py-3"><div className="flex justify-between gap-3"><span>No. transaksi</span><strong>{receipt.number}</strong></div><div className="flex justify-between gap-3"><span>Tanggal</span><span>{receipt.createdAt ?? '—'}</span></div><div className="flex justify-between gap-3"><span>Pembeli</span><span>{receipt.buyer}</span></div><div className="flex justify-between gap-3"><span>Kasir</span><span>{receipt.cashier}</span></div></section><section className="overflow-x-auto border-b border-dashed border-slate-300 py-3"><table className="w-full min-w-[420px]"><thead><tr className="border-b border-slate-200 text-left"><th className="pb-2">Item</th><th className="pb-2 text-right">Qty</th><th className="pb-2 text-right">Harga</th><th className="pb-2 text-right">Jumlah</th></tr></thead><tbody>{receipt.items.map((item) => <tr key={item.id}><td className="py-2 pr-2 font-sans font-medium">{item.name}</td><td className="py-2 text-right">{formatNumber(item.quantity)}{item.unit ? ` ${item.unit}` : ''}</td><td className="py-2 text-right">{formatCurrency(item.price)}</td><td className="py-2 text-right font-semibold">{formatCurrency(item.total)}</td></tr>)}</tbody></table></section><section className="space-y-2 border-b border-dashed border-slate-300 py-3"><div className="flex justify-between text-sm font-bold"><span>TOTAL</span><span>{formatCurrency(receipt.total)}</span></div><div className="flex justify-between text-slate-600"><span>Bayar ({receipt.paymentMethod.toUpperCase()})</span><span>{formatCurrency(receipt.paid)}</span></div><div className="flex justify-between text-slate-600"><span>Kembalian</span><span className="font-semibold text-slate-900">{formatCurrency(receipt.change)}</span></div></section><footer className="pt-4 text-center text-[10px] text-slate-500"><p>Terima kasih atas pembelian Anda.</p><p className="mt-1">Semoga lekas sehat.</p></footer></CardContent></Card></div></>;
}
