import { Head, Link } from '@inertiajs/react';
import { ArrowLeft, Printer } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Empty } from '@/components/ui/empty';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table';
import { formatNumber } from '@/lib/format';

interface Diagnosis { code: string | null; name: string; type: string }
interface Screening { systolic: number | null; diastolic: number | null; pulse: number | null; temperature: number | null; oxygenSaturation: number | null; weight: number | null; height: number | null; respiration: number | null; complaint: string | null }
interface DentalFinding { toothFdi: string; surface: string; findingCode: string; notes: string | null }
interface Examination { anamnesis: string | null; physicalExamination: string | null; education: string | null; notes: string | null; nextControl: string | null; signedAt: string | null; signedBy: string | null; integrityValid: boolean | null; versions: Array<{ version: number; kind: string; reason: string | null; actor: string | null; recordedAt: string | null; anamnesis: string | null; physicalExamination: string | null; odontogram: DentalFinding[] }>; diagnoses: Diagnosis[] }
interface Prescription { id: number; name: string; quantity: string | number; unit: string | null; instructions: string | null }
interface Treatment { id: number; name: string; quantity: number; toothFdi: string | null }
interface Visit { id: number; number: string; clinic: string; clinicType: string | null; doctor: string; date: string | null; status: string; screening: Screening | null; examination: Examination | null; prescriptions: Prescription[]; treatments: Treatment[]; odontogram: DentalFinding[] }
interface Patient { id: number; name: string; medicalRecordNumber: string; nik: string | null; gender: string | null; age: number | null; bloodType: string | null; allergies: string | null }
interface Props { patient: Patient; visits: Visit[]; backUrl: string }

export default function PatientMedicalRecord({ patient, visits, backUrl }: Props) {
    return <><Head title={`Rekam Medis ${patient.name}`} /><div className="space-y-6"><div className="flex items-center justify-between gap-3 print:hidden"><Button asChild size="sm" variant="ghost"><Link href={backUrl}><ArrowLeft className="size-4" />Kembali ke profil pasien</Link></Button><Button onClick={() => window.print()}><Printer className="size-4" />Cetak rekam medis</Button></div>
        <Card className="medical-record-print"><CardContent className="p-6"><p className="text-xs font-semibold uppercase tracking-wider text-neutral-700">Berkas rekam medis pasien</p><div className="mt-2 flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><h2 className="text-2xl font-semibold tracking-tight text-neutral-950">{patient.name}</h2><p className="mt-2 flex flex-wrap gap-x-3 gap-y-1 text-sm text-neutral-600"><span className="font-mono font-semibold text-neutral-700">{patient.medicalRecordNumber}</span><span>NIK: {patient.nik || '—'}</span><span>{patient.gender === 'L' ? 'Laki-laki' : patient.gender === 'P' ? 'Perempuan' : '—'}, {patient.age === null ? 'umur belum diketahui' : `${patient.age} th`}</span><span>Golongan darah: {patient.bloodType || '—'}</span></p></div>{patient.allergies && <div className="max-w-xl rounded-xl border border-red-200 bg-red-50 p-3 text-sm text-red-900"><p className="text-xs font-bold uppercase tracking-wide text-red-700">Riwayat alergi</p><p className="mt-1 font-medium">{patient.allergies}</p></div>}</div></CardContent></Card>
        {visits.length ? visits.map((visit) => <Card className="medical-record-print overflow-hidden" key={visit.id}><div className="flex flex-wrap items-center justify-between gap-3 border-b border-neutral-100 bg-neutral-50 px-5 py-4"><div className="flex flex-wrap items-center gap-3"><span className="font-mono text-sm font-bold text-neutral-900">{visit.number}</span><span className="rounded-full bg-neutral-50 px-2.5 py-1 text-xs font-semibold text-neutral-700">{visit.clinic}</span><span className="text-sm text-neutral-600">Dokter: <strong>{visit.doctor}</strong></span></div><div className="flex items-center gap-3 text-sm text-neutral-500"><span>{visit.date ?? '—'}</span><span className="rounded-full bg-emerald-50 px-2.5 py-1 text-xs font-semibold capitalize text-emerald-700">{visit.status}</span></div></div><CardContent className="space-y-6 p-5">
            {visit.examination?.integrityValid === false && <p className="rounded-xl border border-red-300 bg-red-50 p-4 text-sm font-semibold text-red-900">Integritas riwayat catatan ini tidak valid. Gunakan sumber klinis terverifikasi sebelum mengambil keputusan.</p>}
            {visit.examination?.signedAt && <section className="rounded-xl border border-neutral-200 p-4"><SectionTitle>Finalisasi dan addendum</SectionTitle><p className="text-sm text-neutral-700">Difinalisasi oleh {visit.examination.signedBy ?? 'dokter'} pada {visit.examination.signedAt}.</p><div className="mt-3 space-y-3">{visit.examination.versions.map((version) => <div className="rounded-lg bg-neutral-50 p-3 text-sm" key={version.version}><p className="font-semibold text-neutral-900">Versi {version.version} · {version.kind === 'addendum' ? 'Addendum' : 'Final'} <span className="font-normal text-neutral-600">· {version.actor ?? 'Dokter'} · {version.recordedAt ?? '—'}</span></p>{version.reason && <p className="mt-1 text-neutral-700">Alasan: {version.reason}</p>}<p className="mt-2 whitespace-pre-wrap text-neutral-700"><strong>Anamnesis:</strong> {version.anamnesis || '—'}</p><p className="mt-1 whitespace-pre-wrap text-neutral-700"><strong>Pemeriksaan fisik:</strong> {version.physicalExamination || '—'}</p></div>)}</div></section>}
            {visit.clinicType === 'gigi' && visit.examination?.signedAt && <section><SectionTitle>Riwayat versi odontogram</SectionTitle><div className="space-y-2">{visit.examination.versions.map((version) => <div className="rounded-xl bg-neutral-50 p-3 text-sm" key={version.version}><p className="font-semibold text-neutral-900">Versi {version.version} · {version.kind === 'addendum' ? 'Addendum' : 'Final'}</p><p className="mt-1 text-neutral-700">{version.odontogram.length ? version.odontogram.map((finding) => `${finding.toothFdi} ${dentalSurface(finding.surface)}: ${dentalFinding(finding.findingCode)}`).join('; ') : 'Temuan tidak tercatat'}</p></div>)}</div></section>}
            {visit.screening && <section><SectionTitle>Tanda vital & keluhan</SectionTitle><div className="grid grid-cols-2 gap-3 sm:grid-cols-3 xl:grid-cols-6"><Vital label="Tekanan darah" value={`${visit.screening.systolic ?? '—'}/${visit.screening.diastolic ?? '—'} mmHg`} /><Vital label="Nadi" value={withUnit(visit.screening.pulse, 'x/m')} /><Vital label="Suhu" value={withUnit(visit.screening.temperature, '°C')} /><Vital label="SpO₂" value={withUnit(visit.screening.oxygenSaturation, '%')} /><Vital label="Berat / tinggi" value={`${visit.screening.weight ?? '—'} kg / ${visit.screening.height ?? '—'} cm`} /><Vital label="Respirasi" value={withUnit(visit.screening.respiration, 'x/m')} /></div>{visit.screening.complaint && <p className="mt-3 whitespace-pre-wrap text-sm text-neutral-700"><strong>Keluhan:</strong> {visit.screening.complaint}</p>}</section>}
            {visit.examination && <div className="grid gap-6 lg:grid-cols-2"><section><SectionTitle>Anamnesis & pemeriksaan fisik</SectionTitle><div className="space-y-3 rounded-xl bg-neutral-50 p-4 text-sm"><MedicalNote label="Anamnesis" value={visit.examination.anamnesis} /><MedicalNote label="Pemeriksaan fisik" value={visit.examination.physicalExamination} /><MedicalNote label="Edukasi" value={visit.examination.education} /><MedicalNote label="Catatan dokter" value={visit.examination.notes} />{visit.examination.nextControl && <p className="font-semibold text-neutral-700">Kontrol berikutnya: {visit.examination.nextControl}</p>}</div></section><section><SectionTitle>Diagnosis (ICD-10)</SectionTitle><div className="space-y-2">{visit.examination.diagnoses.length ? visit.examination.diagnoses.map((diagnosis, index) => <div className="flex items-center justify-between gap-3 rounded-xl bg-neutral-50 p-3 text-sm" key={`${diagnosis.code}-${index}`}><p><span className="mr-2 font-mono font-bold text-neutral-700">{diagnosis.code || '—'}</span><span className="font-medium text-neutral-800">{diagnosis.name}</span></p><span className="rounded-full bg-surface px-2 py-1 text-xs capitalize text-neutral-700">{diagnosis.type}</span></div>) : <Empty className="min-h-0 px-3 py-5" description="Diagnosis pada kunjungan ini akan ditampilkan di sini." title="Belum ada diagnosis" />}</div></section></div>}
            {visit.clinicType === 'gigi' && <section><SectionTitle>Odontogram</SectionTitle>{visit.odontogram.length ? <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{visit.odontogram.map((finding) => <div className="rounded-xl border border-neutral-200 p-3 text-sm" key={`${finding.toothFdi}-${finding.surface}`}><p className="font-semibold text-neutral-900">Gigi {finding.toothFdi} · {dentalSurface(finding.surface)}</p><p className="mt-1 text-neutral-700">{dentalFinding(finding.findingCode)}</p>{finding.notes && <p className="mt-1 whitespace-pre-wrap text-neutral-600">{finding.notes}</p>}</div>)}</div> : <Empty className="min-h-0 px-3 py-5" title="Belum ada temuan odontogram" />}</section>}
            <div className="grid gap-6 lg:grid-cols-2"><section><SectionTitle>Resep obat</SectionTitle>{visit.prescriptions.length ? <div className="overflow-x-auto rounded-xl border border-neutral-100"><Table><TableHeader><tr><TableHead>Nama obat</TableHead><TableHead>Jumlah</TableHead><TableHead>Aturan pakai</TableHead></tr></TableHeader><TableBody>{visit.prescriptions.map((item) => <TableRow key={item.id}><TableCell className="font-medium">{item.name}</TableCell><TableCell className="whitespace-nowrap font-mono">{formatNumber(Number(item.quantity))} {item.unit ?? ''}</TableCell><TableCell>{item.instructions || '—'}</TableCell></TableRow>)}</TableBody></Table></div> : <Empty className="min-h-0 px-3 py-5" description="Obat yang diresepkan selama kunjungan akan muncul di sini." title="Belum ada resep obat" />}</section><section><SectionTitle>Tindakan medis</SectionTitle>{visit.treatments.length ? <div className="space-y-2">{visit.treatments.map((item) => <div className="flex justify-between gap-3 rounded-lg bg-neutral-50 px-3 py-2.5 text-sm" key={item.id}><span className="font-medium text-neutral-800">{item.name}{item.toothFdi && <span className="ml-2 text-neutral-500">Gigi {item.toothFdi}</span>}</span><span className="text-neutral-500">{item.quantity}×</span></div>)}</div> : <Empty className="min-h-0 px-3 py-5" description="Tindakan yang tercatat selama kunjungan akan muncul di sini." title="Belum ada tindakan medis" />}</section></div>
        </CardContent></Card>) : <Card className="medical-record-print"><CardContent className="p-5"><Empty className="border-0 bg-transparent" description="Riwayat pemeriksaan, resep, dan tindakan pasien akan muncul setelah kunjungan tercatat." title="Belum ada riwayat rekam medis" /></CardContent></Card>}
    </div></>;
}

function SectionTitle({ children }: { children: string }) { return <h3 className="mb-3 text-xs font-bold uppercase tracking-wider text-neutral-500">{children}</h3>; }
function Vital({ label, value }: { label: string; value: string }) { return <div className="rounded-xl bg-neutral-50 p-3 text-center"><p className="text-xs text-neutral-500">{label}</p><p className="mt-1 text-sm font-semibold text-neutral-800">{value}</p></div>; }
function MedicalNote({ label, value }: { label: string; value: string | null }) { return <p className="whitespace-pre-wrap"><strong>{label}:</strong> {value || '—'}</p>; }
function withUnit(value: number | null, unit: string): string { return value === null ? '—' : `${value} ${unit}`; }
function dentalSurface(code: string): string { return ({ W: 'Seluruh gigi', M: 'Mesial', O: 'Oklusal', D: 'Distal', V: 'Vestibular', L: 'Lingual' } as Record<string, string>)[code] ?? code; }
function dentalFinding(code: string): string { return ({ sound: 'Sehat', caries: 'Karies', missing: 'Hilang', unerupted: 'Belum erupsi', fractured_crown: 'Fraktur mahkota', root_remnant: 'Sisa akar', restored: 'Restorasi' } as Record<string, string>)[code] ?? code; }
