import { Head, router, useForm } from '@inertiajs/react';
import { Plus, Search, UsersRound } from 'lucide-react';
import { useState, type FormEvent } from 'react';
import { Pagination, type PaginationData } from '@/components/dashboard/pagination';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { Field } from '@/components/ui/field';
import { Input } from '@/components/ui/input';
import { NativeSelect } from '@/components/ui/native-select';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table';

interface Staff { id: number; code: string; name: string; gender: string | null; category: string; position: string; sip: string | null; str: string | null; phone: string | null; email: string | null; active: boolean }
interface Option { value: string; label: string }
interface Props { staff: PaginationData & { data: Staff[] }; filters: { search: string; category: string; position: string }; categories: Option[]; positions: Option[] }
const emptyForm = { kode: '', nama: '', jenis_kelamin: '', kategori: 'medis', jabatan: 'dokter', no_sip: '', no_str: '', telepon: '', is_active: true, buat_akun: false, email: '', password: '' };

export default function StaffIndex({ staff, filters, categories, positions }: Props) {
    const [search, setSearch] = useState(filters.search);
    const [category, setCategory] = useState(filters.category);
    const [position, setPosition] = useState(filters.position);
    const [editing, setEditing] = useState<Staff | null>(null);
    const [open, setOpen] = useState(false);
    const form = useForm(emptyForm);
    function filter(event: FormEvent<HTMLFormElement>) { event.preventDefault(); router.get('/master/nakes', { search, kategori: category, jabatan: position }, { preserveState: true, preserveScroll: true, replace: true }); }
    function create() { setEditing(null); form.clearErrors(); form.setData({ ...emptyForm }); setOpen(true); }
    function edit(item: Staff) { setEditing(item); form.clearErrors(); form.setData({ kode: item.code, nama: item.name, jenis_kelamin: item.gender ?? '', kategori: item.category, jabatan: item.position, no_sip: item.sip ?? '', no_str: item.str ?? '', telepon: item.phone ?? '', is_active: item.active, buat_akun: false, email: '', password: '' }); setOpen(true); }
    function save(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const options = { preserveScroll: true, onSuccess: () => setOpen(false) }; if (editing) { form.put(`/master/nakes/${editing.id}`, options); } else { form.post('/master/nakes', options); } }
    function remove(item: Staff) { if (window.confirm(`Hapus data ${item.name}?`)) { router.delete(`/master/nakes/${item.id}`, { preserveScroll: true }); } }

    return <>
        <Head title="Tenaga Kesehatan & Karyawan" />
        <div className="space-y-6"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm font-medium text-violet-700">Manajemen SDM klinik</p><h2 className="mt-1 text-2xl font-semibold tracking-tight text-slate-950">Tenaga kesehatan & karyawan</h2><p className="mt-1 text-sm text-slate-500">Kelola profil, kredensial profesi, status, dan akses login tenaga klinik.</p></div><Button onClick={create}><Plus className="size-4" />Tambah tenaga kerja</Button></div>
            <Card className="overflow-hidden"><CardHeader className="border-b border-slate-100"><div className="flex items-start gap-3"><span className="flex size-10 items-center justify-center rounded-xl bg-violet-50 text-violet-700"><UsersRound className="size-5" /></span><div><CardTitle>Daftar tenaga kerja</CardTitle><CardDescription className="mt-1">{new Intl.NumberFormat('id-ID').format(staff.total)} profil tercatat.</CardDescription></div></div><form className="grid gap-3 pt-3 sm:grid-cols-[minmax(0,1fr)_12rem_13rem_auto]" onSubmit={filter}><Input aria-label="Cari tenaga kerja" onChange={(event) => setSearch(event.target.value)} placeholder="Cari nama atau kode…" value={search} /><NativeSelect aria-label="Kategori tenaga kerja" onChange={(event) => setCategory(event.target.value)} value={category}><option value="">Semua kategori</option>{categories.map((item) => <option key={item.value} value={item.value}>{item.label}</option>)}</NativeSelect><NativeSelect aria-label="Jabatan" onChange={(event) => setPosition(event.target.value)} value={position}><option value="">Semua jabatan</option>{positions.map((item) => <option key={item.value} value={item.value}>{item.label}</option>)}</NativeSelect><Button type="submit"><Search className="size-4" />Filter</Button></form></CardHeader>
                <CardContent className="p-0"><div className="overflow-x-auto"><Table className="min-w-[1050px]"><TableHeader><tr><TableHead>Kode</TableHead><TableHead>Nama</TableHead><TableHead>Kategori</TableHead><TableHead>Jabatan</TableHead><TableHead>SIP / STR</TableHead><TableHead>Akun login</TableHead><TableHead>Status</TableHead><TableHead className="text-right">Aksi</TableHead></tr></TableHeader><TableBody>{staff.data.length ? staff.data.map((item) => <TableRow key={item.id}><TableCell className="font-mono text-xs font-semibold">{item.code}</TableCell><TableCell className="font-medium text-slate-900">{item.name}<span className="mt-1 block text-xs text-slate-500">{item.phone ?? 'Tanpa nomor telepon'}</span></TableCell><TableCell>{item.category === 'medis' ? 'Medis' : 'Non-medis'}</TableCell><TableCell className="capitalize">{positions.find((entry) => entry.value === item.position)?.label ?? item.position}</TableCell><TableCell className="font-mono text-xs">{item.sip ?? item.str ?? '—'}</TableCell><TableCell className="text-xs">{item.email ?? <span className="text-slate-400">Belum ada</span>}</TableCell><TableCell>{item.active ? 'Aktif' : 'Nonaktif'}</TableCell><TableCell><div className="flex justify-end gap-1"><Button onClick={() => edit(item)} size="sm" variant="secondary">Edit</Button><Button onClick={() => remove(item)} size="sm" variant="destructive">Hapus</Button></div></TableCell></TableRow>) : <TableRow><TableCell className="py-10 text-center text-slate-500" colSpan={8}>Belum ada tenaga kerja sesuai filter.</TableCell></TableRow>}</TableBody></Table></div><Pagination pagination={staff} /></CardContent>
            </Card>
        </div>
        <Dialog onOpenChange={setOpen} open={open}><DialogContent className="max-h-[90vh] max-w-2xl overflow-y-auto"><DialogHeader><DialogTitle>{editing ? 'Edit profil tenaga kerja' : 'Tambah tenaga kerja'}</DialogTitle><DialogDescription>Data digunakan pada layanan, jadwal, dan akses klinik.</DialogDescription></DialogHeader><form className="space-y-4" onSubmit={save}>
            <div className="grid gap-4 sm:grid-cols-2"><Field error={form.errors.kode} htmlFor="staff-code" label="Kode SDM" required><Input id="staff-code" maxLength={30} onChange={(event) => form.setData('kode', event.target.value)} required value={form.data.kode} /></Field><Field error={form.errors.jenis_kelamin} htmlFor="staff-gender" label="Jenis kelamin"><NativeSelect id="staff-gender" onChange={(event) => form.setData('jenis_kelamin', event.target.value)} value={form.data.jenis_kelamin}><option value="">Belum dipilih</option><option value="L">Laki-laki</option><option value="P">Perempuan</option></NativeSelect></Field></div>
            <Field error={form.errors.nama} htmlFor="staff-name" label="Nama lengkap" required><Input id="staff-name" maxLength={200} onChange={(event) => form.setData('nama', event.target.value)} required value={form.data.nama} /></Field>
            <div className="grid gap-4 sm:grid-cols-2"><Field error={form.errors.kategori} htmlFor="staff-category" label="Kategori" required><NativeSelect id="staff-category" onChange={(event) => form.setData('kategori', event.target.value)} value={form.data.kategori}>{categories.map((item) => <option key={item.value} value={item.value}>{item.label}</option>)}</NativeSelect></Field><Field error={form.errors.jabatan} htmlFor="staff-position" label="Jabatan" required><NativeSelect id="staff-position" onChange={(event) => form.setData('jabatan', event.target.value)} value={form.data.jabatan}>{positions.map((item) => <option key={item.value} value={item.value}>{item.label}</option>)}</NativeSelect></Field></div>
            <div className="grid gap-4 sm:grid-cols-3"><Field error={form.errors.no_sip} htmlFor="staff-sip" label="Nomor SIP"><Input id="staff-sip" maxLength={100} onChange={(event) => form.setData('no_sip', event.target.value)} value={form.data.no_sip} /></Field><Field error={form.errors.no_str} htmlFor="staff-str" label="Nomor STR"><Input id="staff-str" maxLength={100} onChange={(event) => form.setData('no_str', event.target.value)} value={form.data.no_str} /></Field><Field error={form.errors.telepon} htmlFor="staff-phone" label="Telepon"><Input id="staff-phone" maxLength={20} onChange={(event) => form.setData('telepon', event.target.value)} value={form.data.telepon} /></Field></div>
            {!editing && <div className="space-y-3 rounded-xl border border-slate-200 bg-slate-50 p-4"><label className="flex items-center gap-2 text-sm font-medium text-slate-800"><input checked={form.data.buat_akun} className="size-4 rounded border-slate-300 text-blue-600" onChange={(event) => form.setData('buat_akun', event.target.checked)} type="checkbox" />Buat akun login untuk tenaga kerja ini</label>{form.data.buat_akun && <div className="grid gap-4 border-l-2 border-blue-200 pl-4 sm:grid-cols-2"><Field error={form.errors.email} htmlFor="staff-email" label="Email login" required><Input autoComplete="email" id="staff-email" onChange={(event) => form.setData('email', event.target.value)} required type="email" value={form.data.email} /></Field><Field error={form.errors.password} htmlFor="staff-password" label="Password awal" required><Input autoComplete="new-password" id="staff-password" minLength={6} onChange={(event) => form.setData('password', event.target.value)} required type="password" value={form.data.password} /></Field></div>}</div>}
            <label className="flex items-center gap-2 text-sm text-slate-700"><input checked={form.data.is_active} className="size-4 rounded border-slate-300 text-blue-600" onChange={(event) => form.setData('is_active', event.target.checked)} type="checkbox" />Profil aktif</label><div className="flex justify-end gap-2 border-t border-slate-100 pt-4"><Button onClick={() => setOpen(false)} type="button" variant="secondary">Batal</Button><Button disabled={form.processing} type="submit">{form.processing ? 'Menyimpan…' : 'Simpan profil'}</Button></div>
        </form></DialogContent></Dialog>
    </>;
}
