import { Head, Link, useForm } from '@inertiajs/react';
import { ArrowLeft, Plus } from 'lucide-react';
import { useState, type FormEvent } from 'react';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Field } from '@/components/ui/field';
import { Input } from '@/components/ui/input';
import { Select } from '@/components/ui/select';
import { DatePicker } from '@/components/ui/date-picker';
import { Textarea } from '@/components/ui/textarea';
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table';
import { Empty } from '@/components/ui/empty';
import { Pagination, type PaginationData } from '@/components/dashboard/pagination';
import { formatNumber, formatCurrency } from '@/lib/format';

interface Batch { id: number; number: string; expiry: string | null; stock: number; status: string; source: string; depot: string | null; reference: string; expired: boolean; nearExpiry: boolean }
interface Movement { id: number; date: string; type: string; batch: string | null; quantity: number; before: number; after: number; actor: string | null; reason: string | null; canReturn: boolean }
interface Props { medicine: { id: number; name: string; code: string; stock: number; unit: string; purchasePrice: number }; batches: Batch[]; movements: PaginationData & { data: Movement[] }; depots: { id: number; nama: string }[]; today: string }
type Action = 'receive' | 'reconcile' | 'adjust' | 'transfer' | 'return';
const titles: Record<Action, string> = { receive: 'Penerimaan pengadaan / hibah', reconcile: 'Verifikasi batch fisik', adjust: 'Stok opname / rusak / pemusnahan', transfer: 'Mutasi antar depo', return: 'Retur penyerahan obat' };

export default function StockCard({ medicine, batches, movements, depots }: Props) {
    const [action, setAction] = useState<Action | null>(null);
    const [id, setId] = useState<number | null>(null);
    const initialData = { depo_id: '', nomor_batch: '', expired_at: '', jumlah: '', harga_beli: String(medicine.purchasePrice), sumber: 'pengadaan', referensi: '', jenis: 'opname', alasan: '' };
    const form = useForm(initialData);
    const errors = form.errors as Record<string, string | undefined>;
    function open(next: Action, target?: number) { form.setData(initialData); form.setDefaults(initialData); form.clearErrors(); setId(target ?? null); setAction(next); }
    function save(event: FormEvent) {
        event.preventDefault();
        const url = action === 'receive' ? `/stok/persediaan/${medicine.id}/terima` : action === 'return' ? `/stok/mutasi/${id}/retur` : `/stok/batch/${id}/${action === 'reconcile' ? 'verifikasi' : action === 'adjust' ? 'opname' : 'mutasi'}`;
        form.post(url, { preserveScroll: true, onSuccess: () => setAction(null) });
    }
    return <><Head title={medicine.name + ' — Persediaan'} /><div className="space-y-6">
        <div className="flex flex-wrap items-end justify-between gap-4"><div><Button asChild className="-ml-3 mb-2" size="sm" variant="ghost"><Link href="/stok/persediaan"><ArrowLeft className="size-4" />Persediaan</Link></Button><h2 className="text-2xl font-semibold tracking-tight">{medicine.name}</h2><p className="mt-1 text-sm text-neutral-500">{medicine.code} · Total fisik {formatNumber(medicine.stock)} {medicine.unit}</p></div><Button onClick={() => open('receive')}><Plus className="size-4" />Catat penerimaan</Button></div>
        <Card className="overflow-hidden"><CardHeader><CardTitle>Batch & kedaluwarsa</CardTitle><CardDescription>Penyerahan menggunakan batch layak pakai yang kedaluwarsa paling awal. Saldo karantina wajib diperiksa secara fisik.</CardDescription></CardHeader><div className="overflow-x-auto"><Table className="min-w-[950px]"><TableHeader><TableRow><TableHead>Batch / sumber</TableHead><TableHead>Depo</TableHead><TableHead>Kedaluwarsa</TableHead><TableHead>Saldo</TableHead><TableHead>Kondisi</TableHead><TableHead>Aksi</TableHead></TableRow></TableHeader><TableBody>{batches.length ? batches.map((batch) => <TableRow key={batch.id}><TableCell><p className="font-mono text-xs font-semibold">{batch.number}</p><p className="mt-1 text-xs text-neutral-500">{batch.source} · {batch.reference}</p></TableCell><TableCell>{batch.depot ?? 'Belum diverifikasi'}</TableCell><TableCell>{batch.expiry ?? 'Belum diketahui'}</TableCell><TableCell>{formatNumber(batch.stock)} {medicine.unit}</TableCell><TableCell><Badge variant={batch.expired ? 'cancelled' : batch.status === 'karantina' || batch.nearExpiry ? 'waiting' : 'complete'}>{batch.expired ? 'Kedaluwarsa' : batch.status === 'karantina' ? 'Karantina' : batch.nearExpiry ? '≤ 90 hari' : 'Layak pakai'}</Badge></TableCell><TableCell><div className="flex flex-wrap gap-2">{batch.status === 'karantina' && batch.stock > 0 && <Button size="sm" variant="secondary" onClick={() => open('reconcile', batch.id)}>Verifikasi</Button>}<Button size="sm" variant="secondary" onClick={() => open('adjust', batch.id)}>Opname / kondisi</Button>{batch.stock > 0 && <Button size="sm" variant="ghost" onClick={() => open('transfer', batch.id)}>Mutasi</Button>}</div></TableCell></TableRow>) : <TableRow><TableCell colSpan={6}><Empty title="Belum ada batch" description="Catat penerimaan pertama dengan nomor batch dan kedaluwarsa." size="compact" /></TableCell></TableRow>}</TableBody></Table></div></Card>
        <Card className="overflow-hidden"><CardHeader><CardTitle>Kartu stok & jejak petugas</CardTitle><CardDescription>Setiap perubahan memiliki saldo sebelum/sesudah, batch, alasan, dan petugas.</CardDescription></CardHeader><div className="overflow-x-auto"><Table className="min-w-[1000px]"><TableHeader><TableRow><TableHead>Waktu / petugas</TableHead><TableHead>Jenis</TableHead><TableHead>Batch</TableHead><TableHead>Jumlah</TableHead><TableHead>Total sebelum → sesudah</TableHead><TableHead>Referensi / alasan</TableHead><TableHead>Aksi</TableHead></TableRow></TableHeader><TableBody>{movements.data.length ? movements.data.map((movement) => <TableRow key={movement.id}><TableCell className="text-xs">{movement.date}<p className="mt-1 text-neutral-500">{movement.actor ?? 'Data historis'}</p></TableCell><TableCell>{movement.type.replaceAll('_', ' ')}</TableCell><TableCell className="font-mono text-xs">{movement.batch ?? 'Historis'}</TableCell><TableCell>{formatNumber(movement.quantity)}</TableCell><TableCell className="font-mono text-xs">{formatNumber(movement.before)} → {formatNumber(movement.after)}</TableCell><TableCell className="max-w-64 text-xs">{movement.reason ?? '—'}</TableCell><TableCell>{movement.canReturn && <Button size="sm" variant="secondary" onClick={() => open('return', movement.id)}>Retur</Button>}</TableCell></TableRow>) : <TableRow><TableCell colSpan={7}><Empty title="Belum ada mutasi stok" size="compact" /></TableCell></TableRow>}</TableBody></Table></div><Pagination pagination={movements} /></Card>
    </div>
    <Dialog open={action !== null} onOpenChange={(open) => { if (!open) setAction(null); }}><DialogContent className="max-h-[90vh] overflow-y-auto"><DialogHeader><DialogTitle>{action ? titles[action] : ''}</DialogTitle><DialogDescription>{medicine.name} · Satuan {medicine.unit}. Semua perubahan tercatat pada kartu stok.</DialogDescription></DialogHeader><form onSubmit={save} className="space-y-4">
        {action === 'adjust' && <Field label="Jenis pencatatan" htmlFor="adjust-type"><Select id="adjust-type" value={form.data.jenis} onChange={(event) => form.setData('jenis', event.target.value)}><option value="opname">Stok opname — saldo fisik baru</option><option value="rusak">Barang rusak — jumlah dikeluarkan</option><option value="pemusnahan">Pemusnahan — jumlah dikeluarkan</option></Select></Field>}
        <Field label={action === 'adjust' && form.data.jenis === 'opname' ? 'Saldo batch hasil hitung fisik' : 'Jumlah'} htmlFor="stock-quantity" error={errors.jumlah} required><Input id="stock-quantity" type="number" min={action === 'return' ? 1 : action === 'adjust' ? 0 : 0.01} step={action === 'return' ? '1' : '0.01'} value={form.data.jumlah} onChange={(event) => form.setData('jumlah', event.target.value)} required /></Field>
        {['receive', 'reconcile', 'transfer'].includes(action ?? '') && <Field label="Depo tujuan" htmlFor="stock-depot" error={errors.depo_id} required><Select id="stock-depot" value={form.data.depo_id} onChange={(event) => form.setData('depo_id', event.target.value)} required><option value="">Pilih depo</option>{depots.map((depot) => <option key={depot.id} value={depot.id}>{depot.nama}</option>)}</Select></Field>}
        {['receive', 'reconcile'].includes(action ?? '') && <><Field label="Nomor batch fisik" htmlFor="stock-batch" error={errors.nomor_batch} required><Input id="stock-batch" value={form.data.nomor_batch} onChange={(event) => form.setData('nomor_batch', event.target.value)} required /></Field><Field label="Tanggal kedaluwarsa" htmlFor="stock-expiry" error={errors.expired_at} required><DatePicker id="stock-expiry" value={form.data.expired_at} onChange={(event) => form.setData('expired_at', event.target.value)} required /></Field><Field label="Referensi penerimaan / bukti verifikasi" htmlFor="stock-reference" error={errors.referensi} required><Input id="stock-reference" value={form.data.referensi} onChange={(event) => form.setData('referensi', event.target.value)} required /></Field></>}
        {action === 'receive' && <><Field label="Sumber penerimaan" htmlFor="stock-source"><Select id="stock-source" value={form.data.sumber} onChange={(event) => form.setData('sumber', event.target.value)}><option value="pengadaan">Pengadaan anggaran instansi</option><option value="hibah">Hibah</option></Select></Field><Field label="Biaya per satuan stok (Rp)" htmlFor="stock-cost" error={errors.harga_beli} required><Input id="stock-cost" type="number" min="0" step="0.01" value={form.data.harga_beli} onChange={(event) => form.setData('harga_beli', event.target.value)} required /><p className="text-xs text-neutral-500">Nilai inventaris dan pemakaian anggaran; {formatCurrency(Number(form.data.harga_beli || 0))} per {medicine.unit}.</p></Field></>}
        {['adjust', 'transfer', 'return'].includes(action ?? '') && <Field label="Alasan / bukti pencatatan" htmlFor="stock-reason" error={errors.alasan} required><Textarea id="stock-reason" value={form.data.alasan} onChange={(event) => form.setData('alasan', event.target.value)} required /></Field>}
        {errors.items && <p className="text-sm text-red-700" role="alert">{errors.items}</p>}
        <div className="flex justify-end gap-2"><Button type="button" variant="secondary" onClick={() => setAction(null)}>Batal</Button><Button disabled={form.processing} type="submit">{form.processing ? 'Menyimpan…' : 'Simpan pencatatan'}</Button></div>
    </form></DialogContent></Dialog></>;
}
